FROM node:16.13.0
RUN npm install -g npm@8.1.4 
WORKDIR /app
RUN npx create-react-app cocohub -y
RUN  rm -r cocohub/node_modules && mv cocohub/* . && mv cocohub/.[!.]* . \
    && npm install
RUN cd /app
RUN npm i react-draggable && npm i react-icons && npm i axios && npm i react-loader-spinner
CMD ["npm","start"]