sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dogliy/cocohub-client ./client
  - docker build -t dogliy/cocohub-nginx ./nginx
  - docker build -t dogliy/cocohub-backend ./backend

script:
  - echo "script"

after_success:
  - echo "after_success"
  - docker push dogliy/cocohub-client
  - docker push dogliy/cocohub-nginx
  - docker push dogliy/cocohub-backend

  
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  region: "eu-west-1"
  app: "cocohub-app"
  env: "Cocohubapp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-745665539209"
  bucket_path: "cocohub-app"
  on:
    branch: master
