version: '3'


services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - COCOHUB_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJ1c2VyX2lkIjoyNjYzLCJhdWQiOiJwb3N0Z3JhcGhpbGUifQ.31R0Fg-3XWlJtmEn66tR3A_T86XgjlAEdbE0WKj5p80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80 
    depends_on:
      - client
      - backend 
    
    