version: '3'

services:
  client:
    mem_limit: 128m
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
  nginx:
    mem_limit: 128m
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80  
    depends_on:
      - client
      - backend 
  backend:
    mem_limit: 128m
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
  

    
    