version: '3'


services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./backend:/app
