version: '3'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80 
    depends_on:
      - client
      - backend 
    
    